### ISSUE TITLE
[Help]: 求大老995 Could not deserialize engine. See log for details.

### ISSUE THREAD

**Issue by yeh111w** [laugh12321/TensorRT-YOLO#32]
```
[I] Loading bytes from YoloS4000img.engine
[E] 1: [runtime.cpp::nvinfer1::Runtime::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
[!] Could not deserialize engine. See log for details.
Traceback (most recent call last):
  File "D:\python test\yolov10\model\inferTest.py", line 80, in <module>
    main()
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\rich_click\rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\python test\yolov10\model\inferTest.py", line 45, in main
    model = TRTYOLO(engine)
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\tensorrt_yolo\infer\yolo.py", line 103, in __init__
    self._engine, _ = invoke_if_callable(EngineFromBytes(BytesFromPath(engine_path)))
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\polygraphy\util\util.py", line 678, in invoke_if_callable
    ret = func(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\polygraphy\backend\base\loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\polygraphy\util\util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\polygraphy\backend\trt\loader.py", line 665, in call_impl
    G_LOGGER.critical("Could not deserialize engine. See log for details.")
  File "C:\Users\admin\anaconda3\envs\yolov10\lib\site-packages\polygraphy\logger\logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Could not deserialize engine. See log for details.
```

**Comment by laugh12321** [comment]
1. 这个是使用`ptq_calibration.py`量化出现的问题吗？
2. 有没有详细的日志？
3. 模型是否已经使用`trtyolo`导出为带插件的ONNX?

**Comment by yeh111w** [comment]
1.这是detect.py的执行结果
2.我不清楚详细日志的位子
3.我试过了但显示
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/139565794/1334d4ca-f2c0-457c-948c-4123b84b47cb)

**Comment by laugh12321** [comment]
1. 首先，整个项目的推理都是建立在已经加载NMS插件且导出为engine的基础上的，没有NMS插件的模型是无法使用项目代码推理的。

1. 其次，YOLOv10导出在其他issue中已经回答，可参考 https://github.com/laugh12321/TensorRT-YOLO/issues/28#issuecomment-2135142446 进行操作。

**Comment by yeh111w** [comment]
> 1. 首先，整个项目的推理都是建立在已经加载NMS插件且导出为engine的基础上的，没有NMS插件的模型是无法使用项目代码推理的。
> 2. 其次，YOLOv10导出在其他issue中已经回答，可参考 [[Help]: how to export yolov10 to onnx? #28 (comment)](https://github.com/laugh12321/TensorRT-YOLO/issues/28#issuecomment-2135142446) 进行操作。



> 1. 首先，整个项目的推理都是建立在已经加载NMS插件且导出为engine的基础上的，没有NMS插件的模型是无法使用项目代码推理的。
> 2. 其次，YOLOv10导出在其他issue中已经回答，可参考 [[Help]: how to export yolov10 to onnx? #28 (comment)](https://github.com/laugh12321/TensorRT-YOLO/issues/28#issuecomment-2135142446) 进行操作。

ERROR: 6: The engine plan file is not compatible with this version of TensorRT, expecting library version 8.6.0.12 got 8.6.1.6, please rebuild.
ERROR: 2: [engine.cpp::nvinfer1::rt::deserializeEngine::934] Error Code 2: Internal Error (Assertion engine->deserialize(start, size, allocator, runtime) failed. )

我的版本好像不对 我需要换版本吗?

**Comment by laugh12321** [comment]
你可以参考`demo/detect`中的例子进行修改。

- 如果你使用的是Python 则读取摄像头数据转为`np.array`后再进行前处理 (参考[batcher.py#L153](https://github.com/laugh12321/TensorRT-YOLO/blob/115fafbc69fa89890b71c9837fdf30bcecb23ab7/tensorrt_yolo/infer/batcher.py#L153)), 然后将相关参数传递给`infer`方法。
- 如果你使用的是C++ 则读取摄像头数据转为`deploy::Image`结构体类型的数据后将相关参数传递给模型的`predict`方法。

建议使用C++实现，Python版本比C++慢两倍左右。且C++版本支持硬解码数据作为输入推理。
